# Generated by Django 4.2 on 2023-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0004_account_dob_account_approvedvac_account_availablevac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accId',
            field=models.IntegerField(default=0),
        ),
    ]
