# Generated by Django 4.2.1 on 2023-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0006_employee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="username",
            new_name="Name",
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
