# Generated by Django 4.2.1 on 2023-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0007_rename_username_employee_name_employee_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="is_superuser",
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1, null=True
            ),
        ),
    ]
