# Generated by Django 4.2.1 on 2023-05-21 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0008_remove_employee_is_active_remove_employee_is_admin_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="DOB",
            new_name="Birth_date",
        ),
    ]
