# Generated by Django 4.2.1 on 2023-05-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HR", "0009_rename_dob_employee_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="Name",
            field=models.CharField(max_length=20),
        ),
    ]
