# Generated by Django 4.2.1 on 2023-05-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0012_rename_birth_date_employee_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Name',
            new_name='username',
        ),
    ]
