# Generated by Django 4.2.1 on 2023-05-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0013_rename_name_employee_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='DOB',
            new_name='Birth_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='Name',
        ),
    ]
