# Generated by Django 4.2.1 on 2023-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0014_rename_dob_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TextField(max_length=20)),
                ('end_date', models.TextField(max_length=20)),
                ('employee', models.IntegerField()),
                ('reason', models.TextField(max_length=260)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='accId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
